### ISSUE TITLE
Release publishing stopped working

### ISSUE THREAD

**Issue by mblomdahl** [tchupp/actions-terraform-pr#28]
Hello again @ebachle & @tchupp! Thanks for the efforts on #25, I posted a comment there after my failing attempts to use it. I just found that on the GitHub Marketplace page, the latest version published is `v1.0.13`:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/786326/209884344-832867a8-3b3a-4a85-9c42-c7d5c04654d3.png">

So, I thought the publishing might deserve its own issue to track. Do you have any ideas what could have broke around `v1.0.14`?

**Comment by ebachle** [comment]
I think this is just a matter of me checking a box when I publish the release. Let me try when I ship the last fix for #25 and see if that does something.  If it's not that, then I'll have to look into what else we're missing.  I'll let you know!

**Comment by ebachle** [comment]
Ah... 
![image](https://user-images.githubusercontent.com/2569154/209990104-ac90b230-060b-4fd3-b982-8b74d3931b40.png)

I'll have to wait for @tchupp to get back from vacation as I'm loath to sign it on his behalf, even though it'll let me!  I'll chat with him next week and we'll figure it out.  I don't see a reason we wouldn't publish it.

**Comment by tchupp** [comment]
Sorry for the delay on this, but it should all be good now!

![image](https://user-images.githubusercontent.com/7855170/210419766-ab34b7d5-cbd7-45fb-8f84-e302270557d0.png)

**Comment by ebachle** [comment]
This one also looks right to me now too.  I think we're good to close this.  Thanks again @mblomdahl!
